version: '3.1'

services:
  app:
    build: .
    restart: always 
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    enviroment:
      - SQLALCHEMY_DATABASE_USI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}

  postgres:
    image: postgres:10
    restart: always
    port:
      - "5434:5432"
    enviroment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
